GPT_PROMPT=''

OMIT_TABLES = [
    'alembic_version',
    'logs_auditoria',
    'archivos',
    'logs_auditoria',
    'relacion_rutas_usuarios',
    'relacion_rutas_roles',
    'rutas',
    'ai_queries',
    'credenciales_de_usuarios'
]
# title format replacements
TITLE_FORMATS = {
    'id_visualizacion':'ID',
    'almacenes':'almacenes',
    'almacen': 'almacén',
    'creacion': 'creación',
    'descripcion': 'descripción',
    'informacion': 'información',
    'categoria': 'categoría',
    'menu': 'menú',
    'telefono': 'teléfono',
    'razon': 'razón',
    'metodo': 'método',
    'transito': 'tránsito',
    'periodico': 'periódico',
    'genero':'género',
    'direccion':'dirección',
    'codigo':'código',
    'contratacion':'contratación',
    'numero':'número',
    'razon':'razón',
    'direccion':'dirección',
    'nomina':'nómina',
    'electronico':'electrónico',
    'ultimo':'último',
    'sesion':'sesión',
    'metodo':'método',
    'comision':'comisión',
    'codigo':'código',
    'actualizacion': 'actualización',
    'ejecucion': 'ejecución',
    'dias':'días',
    'guia':'guía', 
    'transito': 'tránsito',
    'interaccion':'interacción',
    'interacciones':'interacciones',
    'ultima':'última',
    'envio':'envío',
    'maximos':'máximos',
    'minimos':'mínimos',
    'aceptacion':'aceptación',

    'curp':'CURP',
    'rfc':'RFC',
    'rgv':'RGV',
    'iva':'IVA',
    'ieps':'IEPS',
    'isr':'ISR',
    'ish':'ISH',
    'uuid':'UUID',
    
    'id_pago_id_visualizacion':'ID Pago',
    'id_gasto_id_visualizacion':'ID Gasto',
    'id_compra_id_visualizacion':'ID Compra',
    'id_venta_id_visualizacion':'ID Venta',
    'id_proyecto_id_visualizacion':'ID Proyecto',

    'id_almacen_nombre':'Almacén',
    'id_almacen_salida_nombre':'Almacén salida',
    'id_almacen_entrada_nombre':'Almacén entrada',
    'id_proveedor_nombre':'Proveedor',
    'id_categoria_de_gasto_nombre':'Categoría',
    'id_cuenta_de_banco_nombre':'Cuenta de banco',
    'id_cuenta_de_banco_salida_nombre':'Cuenta de banco salida',
    'id_cuenta_de_banco_entrada_nombre':'Cuenta de banco entrada',

    'id_producto_nombre':'Producto',
    'id_producto_unidad_de_medida':'Unidad de medida',
    'id_cliente_nombre':'Cliente',
    'id_cliente_nombre_completo':'Cliente',
    'id_proyecto_nombre':'Proyecto',
    'id_puesto_nombre':'Puesto',
    'id_pregunta_de_brief_pregunta':'Pregunta',
    'id_brief_nombre':'Brief',
    'id_integrante_nombre_completo':'Integrante',
    'id_servicio_nombre':'Servicio',
    'id_espacio_nombre':'Espacio',
    'id_actividad_base_nombre':'Actividad',
    'id_integrante_nombre':'Integrante',
    'id_pago_de_nomina_id_visualizacion':'ID Pago',

    'proveedor.nombre':'Proveedor',
    'compras.proveedor.nombre':'Proveedor',
    'brief.nombre':'Brief',
    'cliente.nombre_completo':'Cliente',
    'almacen_entrada.nombre':'Almacén entrada',
    'almacen_salida.nombre':'Almacén salida',
    'venta.id_visualizacion':'ID Venta',
    'servicio.nombre':'Cliente',
    'espacio.nombre':'Espacio',
    'integrante.nombre_completo':'Integrante',
    'pago_de_nomina.fecha_inicio':'Fecha inicio',
    'pago_de_nomina.fecha_fin':'Fecha fin',

}
BRIEFS_CREACION_CLIENTE = {'¿Hacemos match?'}
BRIEFS_GLOW_UP = {'Brief 0','Brief 1'}

# column names for data imports
TABLE_COLUMN_MAPS = {
    'table_name': {
    }
}
