delete from gastos_y_compras_en_pagos;
delete from gastos;
delete from entrega_de_productos_en_ordenes_de_compra  ;
delete from productos_en_ordenes_de_compra ;
delete from productos_en_transferencias_de_inventario ;
delete from ventas_en_pago_de_comisiones ;
delete from servicios_y_productos_en_ordenes_de_ventas ;
delete from servicios_en_citas;
delete from gastos_y_compras_en_pagos ;
delete from pagos;
delete from ordenes_de_venta ;
delete from ordenes_de_compra ;
delete from inventario;
delete from citas;
delete from ajustes_de_dinero;
delete from transferencias_de_dinero;
delete from ajustes_de_inventario;
delete from productos_en_transferencias_de_inventario  ;
delete from transferencias_de_inventario ;
delete from sueldos_pagados_en_nomina  ;
delete from pagos_de_nomina ;
delete from pago_de_comisiones ;
