delete from gastos_y_compras_en_pagos;
delete from gastos;
delete from productos_en_compras ;
delete from productos_en_transferencias_de_inventario ;
delete from ventas ;
delete from compras ;
delete from productos_en_recepciones_de_compras   ;
delete from recepciones_de_compras  ;
delete from inventario;
delete from ajustes_de_dinero;
delete from transferencias_de_dinero;
delete from ajustes_de_inventario;
delete from productos_en_transferencias_de_inventario  ;
delete from transferencias_de_inventario ;
delete from sueldos_pagados_en_nomina  ;
delete from pagos_de_nomina ;
delete from preguntas_de_briefs ;
delete from briefs;