"""empty message

Revision ID: 006bbc492aec
Revises: fba0f8868d1f
Create Date: 2026-01-17 14:15:24.666140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '006bbc492aec'
down_revision = 'fba0f8868d1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('espacios_de_proyectos',
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estatus', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('precios_de_servicios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_espacio_de_proyecto', sa.UUID(), nullable=False))
        batch_op.create_foreign_key(None, 'espacios_de_proyectos', ['id_espacio_de_proyecto'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('precios_de_servicios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_espacio_de_proyecto')

    op.drop_table('espacios_de_proyectos')
    # ### end Alembic commands ###
