"""empty message

Revision ID: 0c928087c6a4
Revises: 6e737a46a444
Create Date: 2026-01-17 17:43:46.255885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c928087c6a4'
down_revision = '6e737a46a444'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proyectos_en_ventas', schema=None) as batch_op:
        batch_op.alter_column('id_proyecto',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proyectos_en_ventas', schema=None) as batch_op:
        batch_op.alter_column('id_proyecto',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###
