"""empty message

Revision ID: 1506fdfe17aa
Revises: f872652dee7f
Create Date: 2025-12-03 17:09:56.089012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1506fdfe17aa'
down_revision = 'f872652dee7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_completo', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('razon_social', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('regimen_fiscal', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('domicilio_fiscal', sa.String(length=255), nullable=True))
        batch_op.drop_column('tipo_de_cliente')
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('tipo_de_cliente', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('domicilio_fiscal')
        batch_op.drop_column('regimen_fiscal')
        batch_op.drop_column('razon_social')
        batch_op.drop_column('nombre_completo')

    # ### end Alembic commands ###
