"""empty message

Revision ID: 25c76cad56c6
Revises: 0c928087c6a4
Create Date: 2026-01-17 17:59:19.435562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25c76cad56c6'
down_revision = '0c928087c6a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('precios_de_servicios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_stripe', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('precios_de_servicios', schema=None) as batch_op:
        batch_op.drop_column('id_stripe')

    # ### end Alembic commands ###
