"""empty message

Revision ID: 30190a292dfe
Revises: 9428345d93f2
Create Date: 2025-12-03 22:25:57.937857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30190a292dfe'
down_revision = '9428345d93f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.alter_column('id_cuenta_de_banco',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('iva',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('importe_total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.alter_column('importe_total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('iva',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('id_cuenta_de_banco',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###
