"""empty message

Revision ID: 319b7c109dee
Revises: 433efb0a4bc2
Create Date: 2025-11-26 17:43:25.060822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '319b7c109dee'
down_revision = '433efb0a4bc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('briefs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_servicio', sa.UUID(), nullable=False))
        batch_op.create_foreign_key(None, 'servicios', ['id_servicio'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('briefs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_servicio')

    # ### end Alembic commands ###
