"""empty message

Revision ID: 3f1b8aa45485
Revises: 
Create Date: 2025-11-26 10:58:46.727343

"""
from alembic import op
import sqlalchemy as sa
from python.models.sistema import EncryptedColumn

# revision identifiers, used by Alembic.
revision = '3f1b8aa45485'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('almacenes',
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('estatus', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('archivos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre_del_archivo', sa.String(length=255), nullable=True),
    sa.Column('tabla_origen', sa.String(length=255), nullable=False),
    sa.Column('id_registro', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('ruta_s3', sa.String(length=255), nullable=False),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=False),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('briefs',
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categorias_de_gastos',
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estatus', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categorias_de_productos',
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('estatus', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categorias_de_reportes',
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('estatus', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clientes',
    sa.Column('tipo_de_cliente', sa.String(length=255), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('rfc', EncryptedColumn(length=255), nullable=True),
    sa.Column('direccion', EncryptedColumn(length=255), nullable=True),
    sa.Column('codigo_postal', EncryptedColumn(length=255), nullable=True),
    sa.Column('telefono', EncryptedColumn(length=255), nullable=True),
    sa.Column('correo_electronico', EncryptedColumn(length=255), nullable=True),
    sa.Column('contrasena', sa.String(length=255), nullable=False),
    sa.Column('estatus', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logs_auditoria',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tabla', sa.String(length=255), nullable=False),
    sa.Column('id_registro', sa.String(length=255), nullable=False),
    sa.Column('usuario', sa.String(length=255), server_default='Desconocido', nullable=True),
    sa.Column('accion', sa.String(length=1000), nullable=False),
    sa.Column('datos_anteriores', sa.Text(), nullable=True),
    sa.Column('datos_nuevos', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proveedores',
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('razon_social', sa.String(length=255), nullable=True),
    sa.Column('rfc', EncryptedColumn(length=255), nullable=True),
    sa.Column('direccion', EncryptedColumn(length=255), nullable=True),
    sa.Column('codigo_postal', sa.String(length=20), nullable=True),
    sa.Column('telefono', EncryptedColumn(length=255), nullable=True),
    sa.Column('correo_electronico', EncryptedColumn(length=255), nullable=True),
    sa.Column('persona_contacto', sa.String(length=255), nullable=True),
    sa.Column('telefono_contacto', sa.String(length=50), nullable=True),
    sa.Column('correo_electronico_contacto', sa.String(length=255), nullable=True),
    sa.Column('condiciones_pago', sa.String(length=100), nullable=True),
    sa.Column('sitio_web', sa.String(length=255), nullable=True),
    sa.Column('estatus', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('puestos',
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estatus', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('nombre', sa.String(length=1000), nullable=True),
    sa.Column('estatus', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rutas',
    sa.Column('categoria', sa.String(length=255), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('ruta', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servicios',
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estatus', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actividades_base',
    sa.Column('id_servicio', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('entregable', sa.String(length=255), nullable=True),
    sa.Column('horas_estimadas', sa.Float(), nullable=False),
    sa.Column('estatus', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_servicio'], ['servicios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compras',
    sa.Column('id_almacen', sa.UUID(), nullable=False),
    sa.Column('id_proveedor', sa.UUID(), nullable=True),
    sa.Column('fecha_orden', sa.Date(), nullable=False),
    sa.Column('fecha_entrega_estimada', sa.Date(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('descuentos', sa.Float(), nullable=True),
    sa.Column('importe_total', sa.Float(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('estatus', sa.String(length=255), nullable=True),
    sa.Column('estatus_de_pago', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_almacen'], ['almacenes.id'], ),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cotizaciones',
    sa.Column('id_cliente', sa.UUID(), nullable=False),
    sa.Column('id_servicio', sa.UUID(), nullable=False),
    sa.Column('fecha_de_cotizacion', sa.Date(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('importe_total', sa.Float(), nullable=False),
    sa.Column('estatus', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['id_servicio'], ['servicios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integrantes',
    sa.Column('id_puesto', sa.UUID(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=255), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('genero', sa.String(length=255), nullable=True),
    sa.Column('estado_civil', sa.String(length=255), nullable=True),
    sa.Column('direccion', EncryptedColumn(length=255), nullable=True),
    sa.Column('codigo_postal', EncryptedColumn(length=255), nullable=True),
    sa.Column('telefono', EncryptedColumn(length=255), nullable=True),
    sa.Column('correo_electronico', sa.String(length=255), nullable=True),
    sa.Column('fecha_contratacion', sa.Date(), nullable=True),
    sa.Column('fecha_terminacion', sa.Date(), nullable=True),
    sa.Column('numero_seguridad_social', EncryptedColumn(length=255), nullable=True),
    sa.Column('rfc', EncryptedColumn(length=255), nullable=True),
    sa.Column('curp', EncryptedColumn(length=255), nullable=True),
    sa.Column('estatus', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_puesto'], ['puestos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('precios_de_servicios',
    sa.Column('id_servicio', sa.UUID(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('estatus', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_servicio'], ['servicios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preguntas_de_briefs',
    sa.Column('id_brief', sa.UUID(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('pregunta', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_brief'], ['briefs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preguntas_de_calidad_de_servicio',
    sa.Column('id_servicio', sa.UUID(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('pregunta', sa.Text(), nullable=True),
    sa.Column('tipo_de_respuesta', sa.String(length=255), nullable=True),
    sa.Column('opciones', sa.Text(), nullable=True),
    sa.Column('estatus', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_servicio'], ['servicios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preguntas_de_encuesta_de_satisfaccion',
    sa.Column('id_servicio', sa.UUID(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('pregunta', sa.Text(), nullable=True),
    sa.Column('tipo_de_respuesta', sa.String(length=255), nullable=True),
    sa.Column('opciones', sa.Text(), nullable=True),
    sa.Column('estatus', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_servicio'], ['servicios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productos',
    sa.Column('id_categoria_de_producto', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('inventariable', sa.String(length=255), nullable=False),
    sa.Column('unidad_de_medida', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('estatus', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria_de_producto'], ['categorias_de_productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relacion_rutas_roles',
    sa.Column('id_ruta', sa.UUID(), nullable=False),
    sa.Column('id_rol', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['id_ruta'], ['rutas.id'], ),
    sa.PrimaryKeyConstraint('id_ruta', 'id_rol')
    )
    op.create_table('reportes',
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('id_categoria_de_reporte', sa.UUID(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('ruta_sql', sa.String(length=255), nullable=False),
    sa.Column('estatus', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria_de_reporte'], ['categorias_de_reportes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transferencias_de_inventario',
    sa.Column('id_almacen_salida', sa.UUID(), nullable=False),
    sa.Column('id_almacen_entrada', sa.UUID(), nullable=False),
    sa.Column('fecha_de_transferencia', sa.Date(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('estatus', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_almacen_entrada'], ['almacenes.id'], ),
    sa.ForeignKeyConstraint(['id_almacen_salida'], ['almacenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id_rol', sa.UUID(), nullable=True),
    sa.Column('nombre', sa.String(length=1000), nullable=False),
    sa.Column('correo_electronico', sa.String(length=120), nullable=False),
    sa.Column('contrasena', sa.String(length=255), nullable=False),
    sa.Column('contrasena_api', sa.UUID(), nullable=True),
    sa.Column('intentos_de_inicio_de_sesion', sa.Integer(), nullable=True),
    sa.Column('ultima_sesion', sa.DateTime(), nullable=True),
    sa.Column('ultimo_cambio_de_contrasena', sa.Date(), nullable=True),
    sa.Column('codigo_unico', sa.UUID(), nullable=True),
    sa.Column('codigo_unico_login', sa.Text(), nullable=True),
    sa.Column('codigo_unico_expira', sa.DateTime(), nullable=True),
    sa.Column('estatus', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo_electronico')
    )
    op.create_table('ventas',
    sa.Column('id_servicio', sa.UUID(), nullable=False),
    sa.Column('id_cliente', sa.UUID(), nullable=False),
    sa.Column('id_stripe', sa.String(length=255), nullable=True),
    sa.Column('espacio_de_proyecto', sa.String(length=255), nullable=True),
    sa.Column('importe', sa.Float(), nullable=False),
    sa.Column('tipo_de_iva', sa.String(length=255), nullable=True),
    sa.Column('iva', sa.Float(), nullable=False),
    sa.Column('importe_total', sa.Float(), nullable=False),
    sa.Column('estatus', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['id_servicio'], ['servicios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agenda',
    sa.Column('id_integrante', sa.UUID(), nullable=True),
    sa.Column('id_cliente', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('motivo_de_cancelacion', sa.Text(), nullable=True),
    sa.Column('estatus', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['id_integrante'], ['integrantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ajustes_de_inventario',
    sa.Column('id_almacen', sa.UUID(), nullable=False),
    sa.Column('id_producto', sa.UUID(), nullable=False),
    sa.Column('fecha_de_ajuste', sa.Date(), nullable=True),
    sa.Column('tipo_de_ajuste', sa.String(length=10), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('estatus', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_almacen'], ['almacenes.id'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credenciales_de_usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.UUID(), nullable=False),
    sa.Column('id_credenciales', sa.String(length=255), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('sign_count', sa.Integer(), nullable=True),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_credenciales')
    )
    op.create_table('cuentas_de_banco',
    sa.Column('id_integrante', sa.UUID(), nullable=True),
    sa.Column('banco', sa.String(length=100), nullable=False),
    sa.Column('tipo_de_cuenta', sa.String(length=100), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('numero_de_cuenta', EncryptedColumn(length=255), nullable=True),
    sa.Column('clabe', EncryptedColumn(length=255), nullable=True),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('estatus', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_integrante'], ['integrantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalle_de_cotizaciones',
    sa.Column('id_cotizacion', sa.UUID(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_cotizacion'], ['cotizaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventario',
    sa.Column('id_almacen', sa.UUID(), nullable=False),
    sa.Column('id_producto', sa.UUID(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('cantidad_en_transito', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_almacen'], ['almacenes.id'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('precios_de_proveedores',
    sa.Column('id_proveedor', sa.UUID(), nullable=False),
    sa.Column('id_producto', sa.UUID(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('estatus', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productos_en_compras',
    sa.Column('id_compra', sa.UUID(), nullable=False),
    sa.Column('id_producto', sa.UUID(), nullable=False),
    sa.Column('cantidad_ordenada', sa.Float(), nullable=False),
    sa.Column('cantidad_recibida', sa.Float(), nullable=True),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('descuento_porcentaje', sa.Float(), nullable=True),
    sa.Column('importe_total', sa.Float(), nullable=True),
    sa.Column('fecha_entrega_estimada', sa.Date(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('estatus', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_compra'], ['compras.id'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productos_en_transferencias_de_inventario',
    sa.Column('id_transferencia_de_inventario', sa.UUID(), nullable=False),
    sa.Column('id_producto', sa.UUID(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['id_transferencia_de_inventario'], ['transferencias_de_inventario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proyectos',
    sa.Column('id_venta', sa.UUID(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('estatus', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_venta'], ['ventas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recepciones_de_compras',
    sa.Column('id_almacen', sa.UUID(), nullable=False),
    sa.Column('id_compra', sa.UUID(), nullable=False),
    sa.Column('fecha_entrega', sa.Date(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('estatus', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_almacen'], ['almacenes.id'], ),
    sa.ForeignKeyConstraint(['id_compra'], ['compras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sueldos_de_integrantes',
    sa.Column('id_integrante', sa.UUID(), nullable=False),
    sa.Column('sueldo', sa.Float(), nullable=False),
    sa.Column('estatus', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_integrante'], ['integrantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actividades',
    sa.Column('id_actividad_base', sa.UUID(), nullable=False),
    sa.Column('id_proyecto', sa.UUID(), nullable=False),
    sa.Column('id_integrante', sa.UUID(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_estimada', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('prioridad', sa.String(length=20), nullable=True),
    sa.Column('horas', sa.Float(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('notas_cierre', sa.Text(), nullable=True),
    sa.Column('comentarios_supervisor', sa.Text(), nullable=True),
    sa.Column('estatus', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_actividad_base'], ['actividades_base.id'], ),
    sa.ForeignKeyConstraint(['id_integrante'], ['integrantes.id'], ),
    sa.ForeignKeyConstraint(['id_proyecto'], ['proyectos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ajustes_de_dinero',
    sa.Column('id_cuenta_de_banco', sa.UUID(), nullable=False),
    sa.Column('fecha_de_ajuste', sa.Date(), nullable=True),
    sa.Column('tipo_de_ajuste', sa.String(length=10), nullable=False),
    sa.Column('importe', sa.Float(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('estatus', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_cuenta_de_banco'], ['cuentas_de_banco.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calidad_de_servicio_de_proyectos',
    sa.Column('id_cliente', sa.UUID(), nullable=False),
    sa.Column('id_proyecto', sa.UUID(), nullable=False),
    sa.Column('fecha_cierre', sa.Date(), nullable=True),
    sa.Column('estatus', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['id_proyecto'], ['proyectos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('encuesta_de_satisfaccion_de_proyectos',
    sa.Column('id_cliente', sa.UUID(), nullable=False),
    sa.Column('id_proyecto', sa.UUID(), nullable=False),
    sa.Column('fecha_cierre', sa.Date(), nullable=True),
    sa.Column('estatus', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['id_proyecto'], ['proyectos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('envios',
    sa.Column('id_almacen', sa.UUID(), nullable=False),
    sa.Column('id_cliente', sa.UUID(), nullable=False),
    sa.Column('id_proyecto', sa.UUID(), nullable=False),
    sa.Column('id_proveedor', sa.UUID(), nullable=False),
    sa.Column('guia_de_envio', sa.String(length=255), nullable=False),
    sa.Column('fecha_envio', sa.Date(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('estatus', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_almacen'], ['almacenes.id'], ),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedores.id'], ),
    sa.ForeignKeyConstraint(['id_proyecto'], ['proyectos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facturas',
    sa.Column('id_cliente', sa.UUID(), nullable=False),
    sa.Column('id_proyecto', sa.UUID(), nullable=False),
    sa.Column('uso_de_cfdi', sa.String(length=255), nullable=True),
    sa.Column('metodo_de_pago', sa.String(length=255), nullable=True),
    sa.Column('forma_de_pago', sa.String(length=255), nullable=True),
    sa.Column('folio_fiscal_uuid', sa.String(length=255), nullable=True),
    sa.Column('fecha_de_expedicion', sa.Date(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('impuestos', sa.Float(), nullable=False),
    sa.Column('importe_total', sa.Float(), nullable=False),
    sa.Column('importe_cobrado', sa.Float(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('estatus', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['id_proyecto'], ['proyectos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gastos',
    sa.Column('id_categoria_de_gasto', sa.UUID(), nullable=False),
    sa.Column('id_proveedor', sa.UUID(), nullable=False),
    sa.Column('id_cuenta_de_banco', sa.UUID(), nullable=True),
    sa.Column('importe', sa.Float(), nullable=False),
    sa.Column('importe_pagado', sa.Float(), nullable=False),
    sa.Column('fecha_de_gasto', sa.Date(), nullable=True),
    sa.Column('folio_fiscal_uuid', sa.String(), nullable=True),
    sa.Column('fecha_de_comprobante', sa.String(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('estatus', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria_de_gasto'], ['categorias_de_gastos.id'], ),
    sa.ForeignKeyConstraint(['id_cuenta_de_banco'], ['cuentas_de_banco.id'], ),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gastos_recurrentes',
    sa.Column('id_categoria_de_gasto', sa.UUID(), nullable=False),
    sa.Column('id_proveedor', sa.UUID(), nullable=False),
    sa.Column('id_cuenta_de_banco', sa.UUID(), nullable=True),
    sa.Column('importe', sa.Float(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('estatus', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria_de_gasto'], ['categorias_de_gastos.id'], ),
    sa.ForeignKeyConstraint(['id_cuenta_de_banco'], ['cuentas_de_banco.id'], ),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingresos',
    sa.Column('id_cliente', sa.UUID(), nullable=False),
    sa.Column('id_cuenta_de_banco', sa.UUID(), nullable=False),
    sa.Column('forma_de_pago', sa.String(length=255), nullable=True),
    sa.Column('folio_fiscal_uuid', sa.String(length=255), nullable=True),
    sa.Column('fecha_de_expedicion', sa.Date(), nullable=True),
    sa.Column('importe', sa.Float(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('estatus', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['id_cuenta_de_banco'], ['cuentas_de_banco.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagos_administrativos',
    sa.Column('id_proveedor', sa.UUID(), nullable=True),
    sa.Column('id_cuenta_de_banco', sa.UUID(), nullable=True),
    sa.Column('fecha_pago', sa.Date(), nullable=False),
    sa.Column('importe', sa.Float(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('estatus', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_cuenta_de_banco'], ['cuentas_de_banco.id'], ),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagos_de_nomina',
    sa.Column('id_cuenta_de_banco', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('importe_total', sa.Float(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('estatus', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_cuenta_de_banco'], ['cuentas_de_banco.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productos_en_recepciones_de_ordenes_de_compra',
    sa.Column('id_recepcion_de_compra', sa.UUID(), nullable=False),
    sa.Column('id_producto', sa.UUID(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['id_recepcion_de_compra'], ['recepciones_de_compras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transferencias_de_dinero',
    sa.Column('id_cuenta_de_banco_salida', sa.UUID(), nullable=False),
    sa.Column('id_cuenta_de_banco_entrada', sa.UUID(), nullable=False),
    sa.Column('fecha_de_transferencia', sa.Date(), nullable=True),
    sa.Column('importe', sa.Float(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('estatus', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_cuenta_de_banco_entrada'], ['cuentas_de_banco.id'], ),
    sa.ForeignKeyConstraint(['id_cuenta_de_banco_salida'], ['cuentas_de_banco.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facturas_en_ingresos',
    sa.Column('id_ingreso', sa.UUID(), nullable=False),
    sa.Column('id_factura', sa.UUID(), nullable=True),
    sa.Column('importe', sa.Float(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_factura'], ['facturas.id'], ),
    sa.ForeignKeyConstraint(['id_ingreso'], ['ingresos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gastos_y_compras_en_pagos',
    sa.Column('id_pago', sa.UUID(), nullable=True),
    sa.Column('id_gasto', sa.UUID(), nullable=True),
    sa.Column('id_compra', sa.UUID(), nullable=True),
    sa.Column('importe', sa.Float(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_compra'], ['compras.id'], ),
    sa.ForeignKeyConstraint(['id_gasto'], ['gastos.id'], ),
    sa.ForeignKeyConstraint(['id_pago'], ['pagos_administrativos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productos_en_envios',
    sa.Column('id_envio', sa.UUID(), nullable=False),
    sa.Column('id_producto', sa.UUID(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_envio'], ['envios.id'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('respuestas_calidad_de_servicio',
    sa.Column('id_calidad_de_servicio_de_proyecto', sa.UUID(), nullable=False),
    sa.Column('id_pregunta_de_calidad_de_servicio', sa.UUID(), nullable=False),
    sa.Column('respuesta', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_calidad_de_servicio_de_proyecto'], ['calidad_de_servicio_de_proyectos.id'], ),
    sa.ForeignKeyConstraint(['id_pregunta_de_calidad_de_servicio'], ['preguntas_de_calidad_de_servicio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('respuestas_encuesta_de_satisfaccion',
    sa.Column('id_encuesta_de_satisfaccion_de_proyecto', sa.UUID(), nullable=False),
    sa.Column('id_pregunta_de_encuesta_de_satisfaccion', sa.UUID(), nullable=False),
    sa.Column('respuesta', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_encuesta_de_satisfaccion_de_proyecto'], ['encuesta_de_satisfaccion_de_proyectos.id'], ),
    sa.ForeignKeyConstraint(['id_pregunta_de_encuesta_de_satisfaccion'], ['preguntas_de_encuesta_de_satisfaccion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servicios_en_facturas',
    sa.Column('id_factura', sa.UUID(), nullable=False),
    sa.Column('id_servicio', sa.UUID(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=True),
    sa.Column('valor_unitario', sa.Float(), nullable=True),
    sa.Column('impuesto', sa.Float(), nullable=True),
    sa.Column('importe', sa.Float(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('estatus', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_factura'], ['facturas.id'], ),
    sa.ForeignKeyConstraint(['id_servicio'], ['servicios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sueldos_pagados_en_nomina',
    sa.Column('id_pago_de_nomina', sa.UUID(), nullable=False),
    sa.Column('id_integrante', sa.UUID(), nullable=False),
    sa.Column('importe', sa.Float(), nullable=False),
    sa.Column('importe_ajuste', sa.Float(), nullable=False),
    sa.Column('importe_total', sa.Float(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_integrante'], ['integrantes.id'], ),
    sa.ForeignKeyConstraint(['id_pago_de_nomina'], ['pagos_de_nomina.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sueldos_pagados_en_nomina')
    op.drop_table('servicios_en_facturas')
    op.drop_table('respuestas_encuesta_de_satisfaccion')
    op.drop_table('respuestas_calidad_de_servicio')
    op.drop_table('productos_en_envios')
    op.drop_table('gastos_y_compras_en_pagos')
    op.drop_table('facturas_en_ingresos')
    op.drop_table('transferencias_de_dinero')
    op.drop_table('productos_en_recepciones_de_ordenes_de_compra')
    op.drop_table('pagos_de_nomina')
    op.drop_table('pagos_administrativos')
    op.drop_table('ingresos')
    op.drop_table('gastos_recurrentes')
    op.drop_table('gastos')
    op.drop_table('facturas')
    op.drop_table('envios')
    op.drop_table('encuesta_de_satisfaccion_de_proyectos')
    op.drop_table('calidad_de_servicio_de_proyectos')
    op.drop_table('ajustes_de_dinero')
    op.drop_table('actividades')
    op.drop_table('sueldos_de_integrantes')
    op.drop_table('recepciones_de_compras')
    op.drop_table('proyectos')
    op.drop_table('productos_en_transferencias_de_inventario')
    op.drop_table('productos_en_compras')
    op.drop_table('precios_de_proveedores')
    op.drop_table('inventario')
    op.drop_table('detalle_de_cotizaciones')
    op.drop_table('cuentas_de_banco')
    op.drop_table('credenciales_de_usuarios')
    op.drop_table('ajustes_de_inventario')
    op.drop_table('agenda')
    op.drop_table('ventas')
    op.drop_table('usuarios')
    op.drop_table('transferencias_de_inventario')
    op.drop_table('reportes')
    op.drop_table('relacion_rutas_roles')
    op.drop_table('productos')
    op.drop_table('preguntas_de_encuesta_de_satisfaccion')
    op.drop_table('preguntas_de_calidad_de_servicio')
    op.drop_table('preguntas_de_briefs')
    op.drop_table('precios_de_servicios')
    op.drop_table('integrantes')
    op.drop_table('cotizaciones')
    op.drop_table('compras')
    op.drop_table('actividades_base')
    op.drop_table('servicios')
    op.drop_table('rutas')
    op.drop_table('roles')
    op.drop_table('puestos')
    op.drop_table('proveedores')
    op.drop_table('logs_auditoria')
    op.drop_table('clientes')
    op.drop_table('categorias_de_reportes')
    op.drop_table('categorias_de_productos')
    op.drop_table('categorias_de_gastos')
    op.drop_table('briefs')
    op.drop_table('archivos')
    op.drop_table('almacenes')
    # ### end Alembic commands ###
