"""empty message

Revision ID: 433efb0a4bc2
Revises: d8cbfdbe32df
Create Date: 2025-11-26 17:40:49.906238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '433efb0a4bc2'
down_revision = 'd8cbfdbe32df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('briefs_de_clientes',
    sa.Column('id_cliente', sa.UUID(), nullable=False),
    sa.Column('id_proyecto', sa.UUID(), nullable=False),
    sa.Column('fecha_cierre', sa.Date(), nullable=True),
    sa.Column('estatus', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['id_proyecto'], ['proyectos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('respuestas_briefs_de_clientes',
    sa.Column('id_brief_de_cliente', sa.UUID(), nullable=False),
    sa.Column('id_pregunta_de_brief', sa.UUID(), nullable=False),
    sa.Column('respuesta', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_brief_de_cliente'], ['briefs_de_clientes.id'], ),
    sa.ForeignKeyConstraint(['id_pregunta_de_brief'], ['preguntas_de_briefs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('respuestas_briefs_de_clientes')
    op.drop_table('briefs_de_clientes')
    # ### end Alembic commands ###
