"""empty message

Revision ID: 514335be9968
Revises: f729b5e569c4
Create Date: 2026-01-17 18:07:15.313408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '514335be9968'
down_revision = 'f729b5e569c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proyectos_en_ventas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metros_cuadrados', sa.Float(), nullable=False))
        batch_op.drop_column('metros_cuadrados_totales')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proyectos_en_ventas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metros_cuadrados_totales', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.drop_column('metros_cuadrados')

    # ### end Alembic commands ###
