"""empty message

Revision ID: 61fea15ee762
Revises: df235137cf3b
Create Date: 2025-12-03 17:45:15.275056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61fea15ee762'
down_revision = 'df235137cf3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('briefs_de_clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_brief', sa.UUID(), nullable=False))
        batch_op.create_foreign_key(None, 'briefs', ['id_brief'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('briefs_de_clientes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_brief')

    # ### end Alembic commands ###
