"""empty message

Revision ID: 6408927bd216
Revises: 6f5d9381d6dc
Create Date: 2026-01-18 01:08:44.620652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6408927bd216'
down_revision = '6f5d9381d6dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actividades', schema=None) as batch_op:
        batch_op.alter_column('id_integrante',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('fecha_inicio',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('horas',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)

    with op.batch_alter_table('proyectos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_cliente', sa.UUID(), nullable=False))
        batch_op.create_foreign_key(None, 'clientes', ['id_cliente'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proyectos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_cliente')

    with op.batch_alter_table('actividades', schema=None) as batch_op:
        batch_op.alter_column('horas',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('fecha_inicio',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('id_integrante',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###
