"""empty message

Revision ID: 6e737a46a444
Revises: db1a8ba4f0dd
Create Date: 2026-01-17 14:50:14.294973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e737a46a444'
down_revision = 'db1a8ba4f0dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proyectos_en_ventas',
    sa.Column('id_venta', sa.UUID(), nullable=False),
    sa.Column('id_proyecto', sa.UUID(), nullable=False),
    sa.Column('id_servicio', sa.UUID(), nullable=False),
    sa.Column('id_espacio_de_proyecto', sa.UUID(), nullable=False),
    sa.Column('metros_cuadrados_totales', sa.Float(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('importe', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_espacio_de_proyecto'], ['espacios_de_proyectos.id'], ),
    sa.ForeignKeyConstraint(['id_proyecto'], ['proyectos.id'], ),
    sa.ForeignKeyConstraint(['id_servicio'], ['servicios.id'], ),
    sa.ForeignKeyConstraint(['id_venta'], ['ventas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_de_venta', sa.Date(), nullable=False))
        batch_op.drop_constraint(batch_op.f('ventas_id_servicio_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('ventas_id_espacio_de_proyecto_fkey'), type_='foreignkey')
        batch_op.drop_column('id_espacio_de_proyecto')
        batch_op.drop_column('precio_unitario')
        batch_op.drop_column('cantidad')
        batch_op.drop_column('id_servicio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_servicio', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('cantidad', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('precio_unitario', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('id_espacio_de_proyecto', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('ventas_id_espacio_de_proyecto_fkey'), 'espacios_de_proyectos', ['id_espacio_de_proyecto'], ['id'])
        batch_op.create_foreign_key(batch_op.f('ventas_id_servicio_fkey'), 'servicios', ['id_servicio'], ['id'])
        batch_op.drop_column('fecha_de_venta')

    op.drop_table('proyectos_en_ventas')
    # ### end Alembic commands ###
