"""empty message

Revision ID: 6f5d9381d6dc
Revises: ae4460ccf76c
Create Date: 2026-01-17 18:51:14.125652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f5d9381d6dc'
down_revision = 'ae4460ccf76c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proyectos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_integrante', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'integrantes', ['id_integrante'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proyectos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_integrante')

    # ### end Alembic commands ###
