"""empty message

Revision ID: 9428345d93f2
Revises: 61fea15ee762
Create Date: 2025-12-03 18:03:15.083314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9428345d93f2'
down_revision = '61fea15ee762'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('briefs_de_clientes', schema=None) as batch_op:
        batch_op.alter_column('id_proyecto',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('briefs_de_clientes', schema=None) as batch_op:
        batch_op.alter_column('id_proyecto',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###
