"""empty message

Revision ID: 9b399979c6cf
Revises: e2674f26cf39
Create Date: 2025-12-03 10:03:18.451195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b399979c6cf'
down_revision = 'e2674f26cf39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('costos_adicionales', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compras', schema=None) as batch_op:
        batch_op.drop_column('costos_adicionales')

    # ### end Alembic commands ###
