"""empty message

Revision ID: ae4460ccf76c
Revises: 514335be9968
Create Date: 2026-01-17 18:46:57.673076

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ae4460ccf76c'
down_revision = '514335be9968'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servicios_en_ventas',
    sa.Column('id_venta', sa.UUID(), nullable=False),
    sa.Column('id_servicio', sa.UUID(), nullable=False),
    sa.Column('id_espacio_de_proyecto', sa.UUID(), nullable=False),
    sa.Column('metros_cuadrados', sa.Float(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('importe', sa.Float(), nullable=False),
    sa.Column('id_precio_stripe', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_espacio_de_proyecto'], ['espacios_de_proyectos.id'], ),
    sa.ForeignKeyConstraint(['id_servicio'], ['servicios.id'], ),
    sa.ForeignKeyConstraint(['id_venta'], ['ventas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('proyectos_en_ventas')
    with op.batch_alter_table('proyectos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_servicio', sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column('id_espacio_de_proyecto', sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column('metros_cuadrados', sa.Float(), nullable=False))
        batch_op.create_foreign_key(None, 'servicios', ['id_servicio'], ['id'])
        batch_op.create_foreign_key(None, 'espacios_de_proyectos', ['id_espacio_de_proyecto'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proyectos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('metros_cuadrados')
        batch_op.drop_column('id_espacio_de_proyecto')
        batch_op.drop_column('id_servicio')

    op.create_table('proyectos_en_ventas',
    sa.Column('id_venta', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id_proyecto', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id_servicio', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id_espacio_de_proyecto', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('cantidad', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('precio_unitario', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('importe', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id_visualizacion', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_de_creacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('fecha_de_actualizacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id_usuario', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id_precio_stripe', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('metros_cuadrados', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_espacio_de_proyecto'], ['espacios_de_proyectos.id'], name=op.f('proyectos_en_ventas_id_espacio_de_proyecto_fkey')),
    sa.ForeignKeyConstraint(['id_proyecto'], ['proyectos.id'], name=op.f('proyectos_en_ventas_id_proyecto_fkey')),
    sa.ForeignKeyConstraint(['id_servicio'], ['servicios.id'], name=op.f('proyectos_en_ventas_id_servicio_fkey')),
    sa.ForeignKeyConstraint(['id_venta'], ['ventas.id'], name=op.f('proyectos_en_ventas_id_venta_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('proyectos_en_ventas_pkey'))
    )
    op.drop_table('servicios_en_ventas')
    # ### end Alembic commands ###
