"""empty message

Revision ID: c69b9237a618
Revises: 6408927bd216
Create Date: 2026-01-18 12:23:42.728607

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c69b9237a618'
down_revision = '6408927bd216'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('espacios',
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estatus', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('actividades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calificacion_cliente', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('notas_cliente', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('aceptacion_de_cliente', sa.String(length=100), nullable=True))

    with op.batch_alter_table('precios_de_servicios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_espacio', sa.UUID(), nullable=False))
        batch_op.drop_constraint(batch_op.f('precios_de_servicios_id_espacio_de_proyecto_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'espacios', ['id_espacio'], ['id'])
        batch_op.drop_column('metros_cuadrados_minimos')
        batch_op.drop_column('metros_cuadrados_maximos')
        batch_op.drop_column('id_espacio_de_proyecto')

    with op.batch_alter_table('proyectos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_espacio', sa.UUID(), nullable=False))
        batch_op.drop_constraint(batch_op.f('proyectos_id_espacio_de_proyecto_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'espacios', ['id_espacio'], ['id'])
        batch_op.drop_column('id_espacio_de_proyecto')

    with op.batch_alter_table('servicios_en_ventas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_espacio', sa.UUID(), nullable=False))
        batch_op.drop_constraint(batch_op.f('servicios_en_ventas_id_espacio_de_proyecto_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'espacios', ['id_espacio'], ['id'])
        batch_op.drop_column('id_espacio_de_proyecto')

    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo_de_descuento', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('descuento', sa.Float(), nullable=False))
    op.drop_table('espacios_de_proyectos')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.drop_column('descuento')
        batch_op.drop_column('codigo_de_descuento')

    with op.batch_alter_table('servicios_en_ventas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_espacio_de_proyecto', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('servicios_en_ventas_id_espacio_de_proyecto_fkey'), 'espacios_de_proyectos', ['id_espacio_de_proyecto'], ['id'])
        batch_op.drop_column('id_espacio')

    with op.batch_alter_table('proyectos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_espacio_de_proyecto', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('proyectos_id_espacio_de_proyecto_fkey'), 'espacios_de_proyectos', ['id_espacio_de_proyecto'], ['id'])
        batch_op.drop_column('id_espacio')

    with op.batch_alter_table('precios_de_servicios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_espacio_de_proyecto', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('metros_cuadrados_maximos', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('metros_cuadrados_minimos', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('precios_de_servicios_id_espacio_de_proyecto_fkey'), 'espacios_de_proyectos', ['id_espacio_de_proyecto'], ['id'])
        batch_op.drop_column('id_espacio')

    with op.batch_alter_table('actividades', schema=None) as batch_op:
        batch_op.drop_column('aceptacion_de_cliente')
        batch_op.drop_column('notas_cliente')
        batch_op.drop_column('calificacion_cliente')

    op.create_table('espacios_de_proyectos',
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('estatus', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id_visualizacion', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_de_creacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('fecha_de_actualizacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id_usuario', sa.UUID(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('espacios_de_proyectos_pkey'))
    )
    op.drop_table('espacios')
    # ### end Alembic commands ###
