"""empty message

Revision ID: c74e0a70a5f4
Revises: 3f1b8aa45485
Create Date: 2025-11-26 11:05:15.859513

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c74e0a70a5f4'
down_revision = '3f1b8aa45485'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos_en_recepciones_de_compras',
    sa.Column('id_recepcion_de_compra', sa.UUID(), nullable=False),
    sa.Column('id_producto', sa.UUID(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['id_recepcion_de_compra'], ['recepciones_de_compras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('productos_en_recepciones_de_ordenes_de_compra')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos_en_recepciones_de_ordenes_de_compra',
    sa.Column('id_recepcion_de_compra', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id_producto', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('cantidad', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('notas', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id_visualizacion', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_de_creacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('fecha_de_actualizacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id_usuario', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id'], name=op.f('productos_en_recepciones_de_ordenes_de_compra_id_producto_fkey')),
    sa.ForeignKeyConstraint(['id_recepcion_de_compra'], ['recepciones_de_compras.id'], name=op.f('productos_en_recepciones_de_ordenes_id_recepcion_de_compra_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('productos_en_recepciones_de_ordenes_de_compra_pkey'))
    )
    op.drop_table('productos_en_recepciones_de_compras')
    # ### end Alembic commands ###
