"""empty message

Revision ID: d8cbfdbe32df
Revises: c74e0a70a5f4
Create Date: 2025-11-26 16:55:30.188837

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd8cbfdbe32df'
down_revision = 'c74e0a70a5f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('facturas_en_ingresos')
    op.drop_table('ingresos')
    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_venta', sa.UUID(), nullable=False))
        batch_op.drop_constraint(batch_op.f('facturas_id_proyecto_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'ventas', ['id_venta'], ['id'])
        batch_op.drop_column('id_proyecto')

    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_cuenta_de_banco', sa.UUID(), nullable=False))
        batch_op.create_foreign_key(None, 'cuentas_de_banco', ['id_cuenta_de_banco'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_cuenta_de_banco')

    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_proyecto', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('facturas_id_proyecto_fkey'), 'proyectos', ['id_proyecto'], ['id'])
        batch_op.drop_column('id_venta')

    op.create_table('facturas_en_ingresos',
    sa.Column('id_ingreso', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id_factura', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('importe', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('notas', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id_visualizacion', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_de_creacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('fecha_de_actualizacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id_usuario', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_factura'], ['facturas.id'], name=op.f('facturas_en_ingresos_id_factura_fkey')),
    sa.ForeignKeyConstraint(['id_ingreso'], ['ingresos.id'], name=op.f('facturas_en_ingresos_id_ingreso_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('facturas_en_ingresos_pkey'))
    )
    op.create_table('ingresos',
    sa.Column('id_cliente', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id_cuenta_de_banco', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('forma_de_pago', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('folio_fiscal_uuid', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('fecha_de_expedicion', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('importe', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('notas', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('estatus', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id_visualizacion', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_de_creacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('fecha_de_actualizacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id_usuario', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id'], name=op.f('ingresos_id_cliente_fkey')),
    sa.ForeignKeyConstraint(['id_cuenta_de_banco'], ['cuentas_de_banco.id'], name=op.f('ingresos_id_cuenta_de_banco_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ingresos_pkey'))
    )
    # ### end Alembic commands ###
