"""empty message

Revision ID: db1a8ba4f0dd
Revises: f780b4623152
Create Date: 2026-01-17 14:31:35.578158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db1a8ba4f0dd'
down_revision = 'f780b4623152'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_espacio_de_proyecto', sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column('cantidad', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('precio_unitario', sa.Float(), nullable=False))
        batch_op.create_foreign_key(None, 'espacios_de_proyectos', ['id_espacio_de_proyecto'], ['id'])
        batch_op.drop_column('espacio_de_proyecto')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('espacio_de_proyecto', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('precio_unitario')
        batch_op.drop_column('cantidad')
        batch_op.drop_column('id_espacio_de_proyecto')

    # ### end Alembic commands ###
