"""empty message

Revision ID: df235137cf3b
Revises: aa40d804bb15
Create Date: 2025-12-03 17:20:13.147089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df235137cf3b'
down_revision = 'aa40d804bb15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('briefs', schema=None) as batch_op:
        batch_op.alter_column('id_servicio',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('briefs', schema=None) as batch_op:
        batch_op.alter_column('id_servicio',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###
