"""empty message

Revision ID: e2674f26cf39
Revises: 319b7c109dee
Create Date: 2025-11-26 17:59:10.467811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2674f26cf39'
down_revision = '319b7c109dee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('briefs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estatus', sa.String(length=255), nullable=True))

    with op.batch_alter_table('preguntas_de_briefs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estatus', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preguntas_de_briefs', schema=None) as batch_op:
        batch_op.drop_column('estatus')

    with op.batch_alter_table('briefs', schema=None) as batch_op:
        batch_op.drop_column('estatus')

    # ### end Alembic commands ###
