"""empty message

Revision ID: ef024bfc83c0
Revises: 30190a292dfe
Create Date: 2026-01-17 11:16:11.422622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef024bfc83c0'
down_revision = '30190a292dfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('respuestas_de_preguntas_de_briefs',
    sa.Column('id_pregunta_de_brief', sa.UUID(), nullable=True),
    sa.Column('respuesta', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_pregunta_de_brief'], ['preguntas_de_briefs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('respuestas_de_preguntas_de_briefs')
    # ### end Alembic commands ###
