"""empty message

Revision ID: f729b5e569c4
Revises: 25c76cad56c6
Create Date: 2026-01-17 18:04:54.561921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f729b5e569c4'
down_revision = '25c76cad56c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proyectos_en_ventas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_precio_stripe', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proyectos_en_ventas', schema=None) as batch_op:
        batch_op.drop_column('id_precio_stripe')

    # ### end Alembic commands ###
