"""empty message

Revision ID: f872652dee7f
Revises: 9b399979c6cf
Create Date: 2025-12-03 13:34:12.057571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f872652dee7f'
down_revision = '9b399979c6cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('importe_pagado', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compras', schema=None) as batch_op:
        batch_op.drop_column('importe_pagado')

    # ### end Alembic commands ###
