"""empty message

Revision ID: fba0f8868d1f
Revises: ef024bfc83c0
Create Date: 2026-01-17 11:22:03.654343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fba0f8868d1f'
down_revision = 'ef024bfc83c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('respuestas_de_preguntas_de_briefs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estatus', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('respuestas_de_preguntas_de_briefs', schema=None) as batch_op:
        batch_op.drop_column('estatus')

    # ### end Alembic commands ###
